var mongoose = require('mongoose');

//var plm = require('passport-local-mongoose');
var Schema = mongoose.Schema;


  var userSchema = new Schema({

    provider: {type: String}, //The provider with which the user authenticated (facebook, twitter, etc.).
    id: {type: String}, //A unique identifier for the user, as generated by the service provider.
    displayName: {type: String}, //The name of this user, suitable for display.
    name: {familyName: String ,givenName: String, middleName: String },
    email: { type: String, required: true, index: { unique: true } },
    password: {type: String, default: ''},
    photos: [],
    first_name: {type: String},
    last_name: {type : String},
    location: { type: String },
    created: {type: Date}

  });

  //userSchema.plugin(plm);

var User = mongoose.model("User", userSchema);
module.exports = User;
